# Create User
POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
  "username" : "Satria",
  "password" : "admin",
  "name" : "Muhamad Satria"
}

###

# Login User
POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "username" : "Satria",
  "password" : "admin"
}

###

# Get Current User
GET http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: d56693e6-85b4-4654-a905-9361ef5d34c0

###

# Update Current User
PATCH http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: d56693e6-85b4-4654-a905-9361ef5d34c0

{
  "name" : "Muhamad Satria new"
}

###

# Logout User
DELETE http://localhost:3000/api/users/logout
Content-Type: application/json
Accept: application/json
Authorization: d56693e6-85b4-4654-a905-9361ef5d34c0

###

# Create Product
POST http://localhost:3000/api/products
Content-Type: application/json
Accept: application/json
Authorization: d56693e6-85b4-4654-a905-9361ef5d34c0

{
  "namaProduct" : "Laptop",
  "deskripsi" : "baru",
  "harga" : 50000,
  "stok" : 10,
  "warna" : "Silver",
  "categori" : "Elektronik"
}


###

# Get Product by ID
GET http://localhost:3000/api/products/15
Content-Type: application/json
Accept: application/json
Authorization: d56693e6-85b4-4654-a905-9361ef5d34c0

###

# Update Product by ID
PUT http://localhost:3000/api/products/15
Content-Type: application/json
Accept: application/json
Authorization: d56693e6-85b4-4654-a905-9361ef5d34c0

{
  "namaProduct": "Updated Laptop",
  "deskripsi": "Updated baru",
  "harga": 1800,
  "stok": 8,
  "warna": "Black",
  "categori": "Elektronik"
}

###

# Delete Product by ID
DELETE http://localhost:3000/api/products/15
Content-Type: application/json
Accept: application/json
Authorization: d56693e6-85b4-4654-a905-9361ef5d34c0
